### ISSUE TITLE
com.tarena.dispatcher.sender.AliSmsSender:157

### ISSUE THREAD

**Issue by guojian0614** [tarena-tech/tarena-pigeon#11]
com.tarena.dispatcher.sender.AliSmsSender:157
   The flow llimit ,  busisness logic should between " SphU.entry" and "entry.exit".
   
    private void limit(String str, String name) throws BlockException {
        Entry entry = null;
        try {
            entry = SphU.entry(name, EntryType.IN, 1, str);
        } catch (BlockException ex) {
            throw ex;
        } finally {
            if (entry != null) {
                entry.exit(1, str);
            }
        }
    }

**Comment by ns3154** [comment]
临时解决方案，等用户对限流有明确需求后，废弃此处硬编码，改为可动态配置

```
        Entry appEntry = null;
        Entry phoneEntry = null;
        try {
            appEntry = SphU.entry("sendAppCodeLimit", EntryType.IN, 1, smsTarget.getAppCode());
            phoneEntry = SphU.entry("sendPhoneLimit", EntryType.IN, 1, smsTarget.getTarget());
            SendSmsResponse sendSmsResponse = doSend(smsTarget);
            return sendSmsResponse.getBody().bizId;
        } catch (BlockException exception) {
            logger.error("触发限流: ", exception);
            throw exception;
        } finally {
            if (null != appEntry) {
                appEntry.exit(1, smsTarget.getAppCode());
            }
            if (null != phoneEntry) {
                phoneEntry.exit(1, smsTarget.getAppCode());
            }
        }
```

**Comment by tarena-tech** [comment]
https://github.com/tarena-tech/tarena-pigeon/pull/13 fixed
